import React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Title } from '@/components/title/title'
import { VariableText } from '@/components/variable-text/variable-text'
import { Button } from '@/components/button/button'
import { Card } from '@/components/cards/card'
import { Grid } from '@/components/grid/grid'

const startingEmojiList: string[] = ['🦆', '🐸', '🦤', '🦖', '🐸', '🦭', '🦖', '🦆', '🦦', '🦦', '🦤', '🦭']
const randomizeEmojis = (emojis: string[]): string[] => {
  const emojiListCopy: string[] = [...emojis]
  for (let i = 0; i < emojiListCopy.length; i += 1) {
    const x = Math.floor(Math.random() * 12)
    const y = Math.floor(Math.random() * 12)
    const z = emojiListCopy[x]
    emojiListCopy[x] = emojiListCopy[y]
    emojiListCopy[y] = z
  }
  return emojiListCopy
}

export const Home = (): JSX.Element => {
  const [emojiList, setEmojiList] = React.useState(randomizeEmojis(startingEmojiList))
  const initialFaceDownValues = emojiList.reduce((reducer, emoji, index) => ({ ...reducer, [index]: true }), {})
  const [faceDown, setFaceDown] = React.useState<Record<number, boolean>>(initialFaceDownValues)
  const [clickedCard, setClickedCard] = React.useState<{ emoji: string, index: number }>({ emoji: '', index: -1 })
  const [numberOfMatches, setNumberOfMatches] = React.useState(0)
  const [numberOfAttempts, setNumberOfAttempts] = React.useState(0)

  const startOver = (): void => {
    setNumberOfMatches(0)
    setNumberOfAttempts(0)
    setFaceDown(initialFaceDownValues)
    setEmojiList(randomizeEmojis(emojiList))
  }
  const flipCard = (index: number, newValue: boolean): void => {
    setTimeout(() => {
      setFaceDown({ ...faceDown, [index]: newValue })
    }, 500)
  }

  const onCardClick = (index: number, emoji: string): void => {
    setFaceDown({ ...faceDown, [index]: !faceDown[index] })

    if (clickedCard.emoji === '') {
      setClickedCard({ index, emoji })
      return
    }

    if (clickedCard.emoji === emoji) {
      setNumberOfMatches(numberOfMatches + 1)
      setNumberOfAttempts(numberOfAttempts + 1)
    } else {
      flipCard(index, faceDown[index])
      flipCard(clickedCard.index, true)
      setNumberOfAttempts(numberOfAttempts + 1)
    }

    setClickedCard({ emoji: '', index: -1 })
  }

  return (
      <>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.main}>
              <div className={styles.navDiv}>
                  <Title text={'Matchinator'}/>
                  <Button text={'Start Over'} onClick={startOver} />
              </div>
              <VariableText text={'Number of Attempts: '} attempts={numberOfAttempts}/>
              <Grid>
                  {emojiList.map(
                    (emoji: string, index: number) => (
                        <Card
                            key={index}
                            emoji={emoji}
                            faceDown={faceDown[index]}
                            whichCard={index}
                            onClick={onCardClick}
                        />
                    )
                  )}
              </Grid>

          </main>
      </>
  )
}

export default Home
