import React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Title } from '@/components/title/title'
import { VariableText } from '@/components/variable-text/variable-text'
import { Card } from '@/components/cards/card'
export default function Home (): JSX.Element {
  return (
      <>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.main}>
              <Title text={'Matchinator'}/>
              <VariableText text={'Click Any Card To Begin'}/>
              <Card faceDown={false} emoji={'⭐️'}/>
              <Card faceDown emoji={'⭐️'}/>
          </main>
      </>
  )
}
